#!/bin/bash

name="mkorcha/phalcon"

php_ver="5.6.22"
phalcon_ver="2.0.13"

docker build -t ${name}:latest -t ${name}:${php_ver}-${phalcon_ver} --build-arg PHP_VERSION="${php_ver}" --build-arg PHALCON_VERSION="${phalcon_ver}" --rm=true --no-cache=true --pull=true src

docker push ${name}:latest
docker push ${name}:${php_ver}-${phalcon_ver}
