nginx:
  image: nginx
  links:
   - php-fpm
  ports:
   - "8080:80"
  volumes:
   - ".:/var/www"
   - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"

php-fpm:
  image: mkorcha/phalcon
  volumes:
   - ".:/var/www"
