version: '2'
services:
  nginx:
    image: nginx
    depends_on:
     - php-fpm
    ports:
     - "8080:80"
    volumes:
     - ".:/var/www"
     - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"

  php-fpm:
    image: mkorcha/phalcon:5.6.26-3.0.1
    volumes:
     - ".:/var/www"
